/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uitest;

import java.awt.CardLayout;
import java.awt.Font;

import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Component;
import java.awt.Point;

/**
 *
 * @author John
 */
public class Page1 extends javax.swing.JPanel {

    /**
     * Creates new form Page1
     */
//    JFrame f;
//    public Page1(JFrame f) {
//        this.f = f;
//        
//    }
//      public Page1(){ 
//        initComponents();
//      }
    JPanel p_main;
    CardLayout layout;

    public Page1(JPanel p_main, CardLayout layout) {
        this.p_main = p_main;
        this.layout = layout;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        p_page1 = new javax.swing.JPanel();
        hanButton = new javax.swing.JButton();
        jungButton = new javax.swing.JButton();
        jungButton.setFont(new Font("문체부 훈민정음체", Font.PLAIN, 30));
        ilButton = new javax.swing.JButton();
        ilButton.setFont(new Font("문체부 훈민정음체", Font.PLAIN, 30));
        yangButton = new javax.swing.JButton();
        yangButton.setFont(new Font("문체부 훈민정음체", Font.PLAIN, 30));
        bunButton = new javax.swing.JButton();
        bunButton.setFont(new Font("문체부 훈민정음체", Font.PLAIN, 30));

        p_page1.setBackground(new java.awt.Color(51, 153, 255));
        p_page1.setToolTipText("첫번째 페이지");

        hanButton.setText("한식");
        hanButton.setFont(new Font("문체부 훈민정음체", Font.PLAIN, 30));
        hanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jungButton.setText("중식");
        jungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ilButton.setText("일식");
        ilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        yangButton.setText("양식");
        yangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        bunButton.setText("분식");
        bunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_page1Layout = new javax.swing.GroupLayout(p_page1);
        p_page1Layout.setHorizontalGroup(
        	p_page1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(p_page1Layout.createSequentialGroup()
        			.addGap(70)
        			.addComponent(hanButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(p_page1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(p_page1Layout.createSequentialGroup()
        					.addGap(104)
        					.addComponent(yangButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        					.addGap(81)
        					.addComponent(bunButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
        				.addGroup(p_page1Layout.createSequentialGroup()
        					.addGap(277)
        					.addComponent(jungButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        					.addGap(68)
        					.addComponent(ilButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(86, Short.MAX_VALUE))
        );
        p_page1Layout.setVerticalGroup(
        	p_page1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(p_page1Layout.createSequentialGroup()
        			.addGroup(p_page1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(p_page1Layout.createSequentialGroup()
        					.addGap(212)
        					.addGroup(p_page1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(ilButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jungButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
        					.addGap(47)
        					.addGroup(p_page1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(bunButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        						.addComponent(yangButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(p_page1Layout.createSequentialGroup()
        					.addGap(60)
        					.addComponent(hanButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(233, Short.MAX_VALUE))
        );
        p_page1.setLayout(p_page1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//new Page2_1(selectList);
//    ((CarpangiMain) f).show("KOREA");

        layout.show(p_main, "KOREA");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        layout.show(p_main, "CHINA");
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        layout.show(p_main, "JAPAN");
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        layout.show(p_main, "USA");
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        layout.show(p_main, "SNACK");
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton hanButton;
    private javax.swing.JButton jungButton;
    private javax.swing.JButton ilButton;
    private javax.swing.JButton yangButton;
    private javax.swing.JButton bunButton;
    private javax.swing.JPanel p_page1;
    // End of variables declaration                   
}