/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uitest;

import java.awt.BorderLayout;
import java.awt.CardLayout;

/**
 *
 * @author John
 */
public class UIFrame extends javax.swing.JFrame {

    private CardLayout layout;
    Page1 page1;
    Page2_1 kp;
    Page2_2 cp;
//    Page2_3 jp;
//    Page2_4 up;
//    Page2_5 sp;
//    Page3 payment;

    /**
     * Creates new form CarpangiMain
     */
    public UIFrame() {

        setTitle("Food Court");

//       page1 = new Page1();
//        getContentPane().add(page1, "MAIN");
//        
//        mp = new Page1(this);
//        kp = new Page2_1(this);
//        cp = new Page2_2();
//        jp = new Page2_3();
//        up = new Page2_4();
//        sp = new Page2_5();
//        payment = new Page3();
        initComponents();//초기화
//        getContentPane().setLayout(cards);
//        p_main.setLayout(new BorderLayout());

        layout = new CardLayout();

        page1 = new Page1(p_main, layout);
        kp = new Page2_1();
        cp = new Page2_2();
//        jp = new Page2_3();
//        up = new Page2_4();
//        sp = new Page2_5();
//        payment = new Page3();

        p_main.setLayout(layout);
        p_main.add(page1, "MAIN");
        p_main.add(kp, "KOREA");
        p_main.add(cp, "CHINA");
//        p_main.add(jp, "JAPAN");
//        p_main.add(up, "USA");
//        p_main.add(sp, "SNACK");

        layout.show(p_main, "MAIN");

//        getContentPane().add(mp, "MAIN");
//        getContentPane().add(kp, "KOREAN");
//        getContentPane().add(cp, "CHINA");
//        getContentPane().add(jp, "JAPAN");
//        getContentPane().add(up, "USA");
//        getContentPane().add(sp, "SNACK");
//        getContentPane().add(payment, "PAY");
//        JOptionPane.showMessageDialog(null, "금액이 부족합니다");
//    cards.show(this, "MAIN");
    }

    public void showPanel(String panelName) {
//        cards.show(this.getContentPane(), panelName);
        layout.show(this, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        b_home = new javax.swing.JButton();
        b_pay = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        p_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_home.setText("홈");
        b_home.setToolTipText("홈으로...");
        b_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_homeActionPerformed(evt);
            }
        });

        b_pay.setText("결제");
        b_pay.setToolTipText("결제하기...");

        b_cancel.setText("RE");
        b_cancel.setToolTipText("취소하기...");

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 466, Short.MAX_VALUE)
                        .addComponent(b_home, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_home, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void b_homeActionPerformed(java.awt.event.ActionEvent evt) {                                       
     this.showPanel("MAIN");
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_home;
    private javax.swing.JButton b_pay;
    public javax.swing.JPanel p_main;
    // End of variables declaration                   
}